# Best Practices

# Using a version tagged starting image
# Combined OS and Java Run Time
# JRE instead of JDK
FROM openjdk:11-jre-slim

# Does not change, Moved to Second instruction
WORKDIR /app

# Added only Jar file
# Added Jar file right before use
ADD target/layerdemo-0.0.1-SNAPSHOT.jar /app/

CMD ["java", "-jar", "layerdemo-0.0.1-SNAPSHOT.jar"]