# First stage called "builder"
FROM openjdk:11-jdk as builder
WORKDIR /project
ADD . /project
RUN ./mvnw package

# Second stage
# Smaller OS footprint using JRE
FROM openjdk:11-jre-slim
WORKDIR /app

# Copy only the Jar from the "builder" stage
COPY  --from=builder /project/target/layerdemo-0.0.1-SNAPSHOT.jar /app

# Run the Jar = Final image only containers Second stage
CMD ["java", "-jar", "layerdemo-0.0.1-SNAPSHOT.jar"]



